### ISSUE TITLE
After deleting extension, no dropdown list as before

### ISSUE THREAD

**Issue by Aurety** [javsezlol1/Stylez#14]
Hello, I had some issues with your (really great extension !) like some styles still applied even if I cleaned the prompt field, so I tried to delete the folder's extension but I can't retrieve the old interface drop down list I had before.. Hope it's clear, I'm not an expert in english.. lol.
Thanks for any help.. It would be good to your plugin to put a button to flush the styles in the prompts.. Maybe it's already here but I never found it.

**Comment by javsezlol1** [comment]
Hi I'm not sure exactly what you mean do you mean the style still applied even if the text wasn't in the prompt box?

**Comment by Aurety** [comment]
Thanks for quick response ! 
 Hard to explain.. :( So, if I pick up a old gen in txt2image who has a style applied to generate another picture with different seed for exemple, or with some words substitutions, even if I erase the style in the prompt, it applied the old style. I didn't have this behavior before the installation of your plugin, and after remove it.. And now, I can't find the old style system with the dropdown list and the field to remove style or add one. I click on the pen and nothing is happening. Before I installed your plugin, I used https://github.com/Haoming02/sd-webui-boomer extension, but your plugin remove his features but maybe this is a clue.. Don't know. I remove it too, to retrieve the standard UI but it doesn't work.. Not sure, it's about your side but I have to try to find a solution.

**Comment by javsezlol1** [comment]
Okay I see. I think the issue is with the boomer pulgin don't use it along side my plug in. It's proberly something to do with how the boomer plug in handles the style bar. Mine just shows or hides it based on a check box it's not written to webui it's all contained in the extension folder. That's all I can say without checking. Proberly also the reason you have the issue with prompt being there even when it's cleared. Try unistalling both plug-ins. Reinstall mine and make sure the hide style bar is unchecked that should bring back the styles bar then see if u have the issue with the generate not changing if you do please let me know.
If not then u can either use my style system or uninstall mine and then install boomer.

Note any styles created in my system will not be converted to work with the old style system
